### ISSUE TITLE
Предложения по улучшению

### ISSUE THREAD

**Issue by DaryaAkimova** [VadimCpp/gsgusev.ru#22]
1. Сделать раздел с кафешками и т.д. 2. Сделать раздел с развлечениями (бильярд, музей, кальян, поищу еще) 3. Добавить инфу про баню местную (гусевскую, такая есть) 4. Добавить инфу про парки, но это под вопросом 5. Написать побольше про ФОК и его возможности (каток, бассейн, допустимое время посещения мб) 6. раздел с объявлениями мб

**Comment by VadimCpp** [comment]
Спасибо, возьму в работу как дойдут руки.

**Comment by VadimCpp** [comment]
Информация неактуальна, Даша уехала, некому развлекаться в Гусеве
