### ISSUE TITLE
[Vue] Убрать пустые render ()

### ISSUE THREAD

**Issue by JiLiZART** [VadimCpp/gsgusev.ru#24]
Заметил что везде по коду пустые `render()` они не нужны если используется `<template>` внутри `*.vue`
https://github.com/vadimcpp/gsgusev.ru/blob/master/src/components/AdminPoselka.vue#L53

**Comment by VadimCpp** [comment]
Исправлено:
https://github.com/VadimCpp/gsgusev.ru/commit/e5241ec4043200d710109f8e1425680786e52223

**Comment by JiLiZART** [comment]
можно это прям в коммите писать через `Fixes #24`
