### ISSUE TITLE
[Vue] подключать стили из файла правильно

### ISSUE THREAD

**Issue by JiLiZART** [VadimCpp/gsgusev.ru#25]
Вместо 
```html
<style lang="scss" scoped>
@import '../assets/scss/admin-poselka.scss';
</style>
```
можно сделать так
```html
<style src="../assets/scss/admin-poselka.scss" lang="scss" scoped></style>
```

PS
по мне так стили компонента должны лежать рядом с компонентом, или быть внутри него, а не в отдельной папке, чтобы можно было этот компонент таскать куда угодно

**Comment by VadimCpp** [comment]
Сайт закрывается. Не актуально
