### ISSUE TITLE
[Vue] оптимизация повторений

### ISSUE THREAD

**Issue by JiLiZART** [VadimCpp/gsgusev.ru#26]
в Vue можно в шаблонах использовать `v-for`, что поможет сократить вот это https://github.com/vadimcpp/gsgusev.ru/blob/master/src/components/BusGusevKgd.vue#L68
до десяти строчек.
Это только то что бросается в глаза, уверен что еще есть места которые можно свернуть до цикла и вынести данные во внешний источник, json файл например, так и удобнее будет потом превратить этот файл в json ответ с сервера

**Comment by VadimCpp** [comment]
Закрыли наконец.
