### ISSUE TITLE
[vue] animation

### ISSUE THREAD

**Issue by VadimCpp** [VadimCpp/gsgusev.ru#28]
При переключении со страницы о нас на главную видно, что анимация работает криво: один блок еще не пропал, а второй - уже отобразился. Это надо исправить.

**Comment by Ufrutov** [comment]
Анимация реализована элементом `<transition>`, который оборачивает нужный блок на странице:

```
<transition name="fade" appear>
    <section> ... </section>
</transition>
```

CSS свойства анимации настраиваются в стилях - _src/assets/scss/components/transition.scss_

> [Vue animation](https://ru.vuejs.org/v2/guide/transitions.html)
