### ISSUE TITLE
Schedule scroll

### ISSUE THREAD

**Issue by VadimCpp** [VadimCpp/gsgusev.ru#39]
Закрепить шапку таблицы при скроле:
http://take.ms/OdGyN

Пользователь должен видеть название столбцов.

Полезная ссыль:
https://ru.vuejs.org/v2/guide/conditional.html#v-show

**Comment by Ufrutov** [comment]
Реализован компонент **TableFixedTHead** (_src/components/TableFixedTHead_)
Он подключается к шаблону как обычно:
```
import TableFixedTHead from '../components/TableFixedTHead'

export default {
  components: {
    TableFixedTHead
  }
}
```
Таблице, в которой используется функционал, присваивается класс **gs-table-fixed-header** и идентификатор **gs-table-fixed** и добавляется элемент компонента `<TableFixedTHead/>`

```
<table class="gs-table-fixed-header" id="gs-table-fixed">
    ...
</table>
<TableFixedTHead/>
```

> Для использования с несколькими таблицами на одной странице компонент будет необходимо немного изменить
