### ISSUE TITLE
Bus schedule

### ISSUE THREAD

**Issue by VadimCpp** [VadimCpp/gsgusev.ru#40]
Благодаря Яндексу у нас есть АПИ Расписаний:
https://tech.yandex.ru/rasp/

Необходимо синхронизировать расписания на сайте. Алгоритм такой:

1. При открытии страницы расписания, происходит обновление расписания.
2. Расписание сохраняется в LocalStorage, отдельно для каждого дня недели.
3. При отсутствии подключения к сети, берем информацию из LocalStorage.
4. При пустом LocalStorage, берем информацию и хардкода.

**Comment by Fedya-Mercuriev** [comment]
Забрал

**Comment by VadimCpp** [comment]
Сайт закрывается. Не актуально
