### ISSUE TITLE
Навигация при смене города

### ISSUE THREAD

**Issue by Ufrutov** [VadimCpp/gsgusev.ru#42]
При смене города навигация работает по старой схеме - главная страница со списком ссылок для Гусева

_Как воспроизвести_:

- Сменить город на Калининград;
- Открыть любую страницу из списка для Калининграда;
- Вернуться на главную кнопкой **GS Gusev**;
- Кнопка **GS Gusev** (назад) в хлебных крошках ведет на список страниц для Гусева;
- При обновлении страницы список страниц обновляется и показывает правильные ссылки для выбранного города;

![screenshot from 2018-04-01 15-19-05](https://user-images.githubusercontent.com/5783554/38173562-62d1e29a-35c0-11e8-8aa5-634171cb981e.png)
![screenshot from 2018-04-01 15-19-57](https://user-images.githubusercontent.com/5783554/38173563-63efc6a6-35c0-11e8-8946-c3c7d7a5ebb5.png)

**Comment by VadimCpp** [comment]
При смене города происходит ошибка.
Подробности на видео:
[http://take.ms/gbFli](http://take.ms/gbFli)

**Comment by VadimCpp** [comment]
Остались нюансы. Создам в отдельных задачах.
