### ISSUE TITLE
Навигация по сайту

### ISSUE THREAD

**Issue by VadimCpp** [VadimCpp/gsgusev.ru#49]
При навигации по сайту переходы происходят неверно.
Пример:
Со страницы http://gsgusev.ru/#/kgd/bus_gusev_kgd 
нажатие на "GS Gusev" прернаправляет пользователя на http://gsgusev.ru/#/

Видео:
[http://take.ms/rHopL](http://take.ms/rHopL)

Это неверно.

При нажатии кнопки "GS Gusev" необходимо перенаправлять пользователя на http://gsgusev.ru/#/kgd/

Аналогичное поведение для страниц c "gsv".

**Comment by Ufrutov** [comment]
75c90df: Improve site pages navigation - use city domain as route prefix (Issue #49)

Для реализации переходов с учетом домена города (/gsv, /kgd) компонент Home.vue разделен на два обособленных - HomeGSV.vue и HomeKGD.vue, но они оба используют общее главное меню из компонента MainMenu.vue - для упрощения дальнейшей разработки. Роутер приложения работает с этими компонентами как с отдельными страницами:

`

    {
      path: '/gsv',
      alias: ['/'],
      name: 'HomeGSV',
      component: HomeGSV,
      meta: {
        title: 'GS Гусев - Главная'
      }
    },
    {
      path: '/kgd',
      name: 'HomeKGD',
      component: HomeKGD,
      meta: {
        title: 'GS Гусев - Главная'
      }
    }
`
