### ISSUE TITLE
Ошибка при переключении городов

### ISSUE THREAD

**Issue by VadimCpp** [VadimCpp/gsgusev.ru#50]
При переключении городов не происходит смены url. Это неверно.

Видео:
http://take.ms/iZ6xp

При переключении городов должен меняться url. Это нужно для того, что бы можно было легко поделиться ссылкой.

**Comment by Ufrutov** [comment]
47c9e5a: Improve city switching process (Issue #50)

Для переключения между городами используется один общий метод вместо двух обособленных - он отвечает за выделение активного элемента меню, сохранение выбранного города и перенаправление на соответствующую страницу (HomeGSV.vue, HomeKGD.vue)

**Comment by VadimCpp** [comment]
Исправлено.
